version: "3"

services:
        esxi:
                container_name: esxi
                image: vmware/vcsim
                tty: true
                ports:
                  - "443:443"
                command: ["/vcsim","-l","0.0.0.0:443"]
        pwsh: 
                container_name: pwsh
                image: vmware/powerclicore
                tty: true
                entrypoint: ["/usr/bin/pwsh"]
                volumes:
                  - ./:/root/invoke
                working_dir: /root/invoke
                profiles: 
                  - extra